name: plane_escape
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/plane.png

version: 1.0.0+1